// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: IoT TGG lcd tft

#ifndef _IOT_TGG_LCD_TFT_UI_H
#define _IOT_TGG_LCD_TFT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_Booting_Screen.h"
#include "ui_Home_Page.h"
#include "ui_Settings_Screen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * bootingscreen_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1255442560);    // assets/ezgif-frame-001.png
LV_IMG_DECLARE(ui_img_881007481);    // assets/ezgif-frame-004.png
LV_IMG_DECLARE(ui_img_554368748);    // assets/ezgif-frame-005.png
LV_IMG_DECLARE(ui_img_1282450877);    // assets/ezgif-frame-006.png
LV_IMG_DECLARE(ui_img_200721698);    // assets/ezgif-frame-007.png
LV_IMG_DECLARE(ui_img_1303013389);    // assets/ezgif-frame-008.png
LV_IMG_DECLARE(ui_img_132362840);    // assets/ezgif-frame-009.png
LV_IMG_DECLARE(ui_img_1604149530);    // assets/ezgif-frame-010.png
LV_IMG_DECLARE(ui_img_1255441537);    // assets/ezgif-frame-011.png
LV_IMG_DECLARE(ui_img_527359408);    // assets/ezgif-frame-012.png
LV_IMG_DECLARE(ui_img_1609088587);    // assets/ezgif-frame-013.png
LV_IMG_DECLARE(ui_img_881006458);    // assets/ezgif-frame-014.png
LV_IMG_DECLARE(ui_img_554369771);    // assets/ezgif-frame-015.png
LV_IMG_DECLARE(ui_img_1282451900);    // assets/ezgif-frame-016.png
LV_IMG_DECLARE(ui_img_200722721);    // assets/ezgif-frame-017.png
LV_IMG_DECLARE(ui_img_1303012366);    // assets/ezgif-frame-018.png
LV_IMG_DECLARE(ui_img_132363863);    // assets/ezgif-frame-019.png
LV_IMG_DECLARE(ui_img_1604146457);    // assets/ezgif-frame-020.png
LV_IMG_DECLARE(ui_img_1255444610);    // assets/ezgif-frame-021.png
LV_IMG_DECLARE(ui_img_527362481);    // assets/ezgif-frame-022.png
LV_IMG_DECLARE(ui_img_1609091660);    // assets/ezgif-frame-023.png
LV_IMG_DECLARE(ui_img_881009531);    // assets/ezgif-frame-024.png
LV_IMG_DECLARE(ui_img_554366698);    // assets/ezgif-frame-025.png
LV_IMG_DECLARE(ui_img_1282448827);    // assets/ezgif-frame-026.png
LV_IMG_DECLARE(ui_img_200719648);    // assets/ezgif-frame-027.png
LV_IMG_DECLARE(ui_img_1303015439);    // assets/ezgif-frame-028.png
LV_IMG_DECLARE(ui_img_132360790);    // assets/ezgif-frame-029.png
LV_IMG_DECLARE(ui_img_1604147480);    // assets/ezgif-frame-030.png
LV_IMG_DECLARE(ui_img_1255443587);    // assets/ezgif-frame-031.png
LV_IMG_DECLARE(ui_img_527361458);    // assets/ezgif-frame-032.png
LV_IMG_DECLARE(ui_img_1609090637);    // assets/ezgif-frame-033.png
LV_IMG_DECLARE(ui_img_881008508);    // assets/ezgif-frame-034.png
LV_IMG_DECLARE(ui_img_554367721);    // assets/ezgif-frame-035.png
LV_IMG_DECLARE(ui_img_1282449850);    // assets/ezgif-frame-036.png
LV_IMG_DECLARE(ui_img_200720671);    // assets/ezgif-frame-037.png
LV_IMG_DECLARE(ui_img_1303014416);    // assets/ezgif-frame-038.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
