// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: IoT TGG lcd tft

#include "ui.h"

lv_obj_t * uic_Image3;
lv_obj_t * uic_Booting_Screen;
lv_obj_t * ui_Booting_Screen = NULL;
lv_obj_t * ui_Image3 = NULL;
// event funtions
void ui_event_Booting_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        bootingscreen_Animation(ui_Image3, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Home_Page, LV_SCR_LOAD_ANIM_FADE_ON, 500, 3900, &ui_Home_Page_screen_init);
    }
}

// build funtions

void ui_Booting_Screen_screen_init(void)
{
    ui_Booting_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Booting_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Booting_Screen, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Booting_Screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);

    ui_Image3 = lv_image_create(ui_Booting_Screen);
    lv_image_set_src(ui_Image3, &ui_img_1255442560);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 270
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Booting_Screen, ui_event_Booting_Screen, LV_EVENT_ALL, NULL);
    uic_Booting_Screen = ui_Booting_Screen;
    uic_Image3 = ui_Image3;

}

void ui_Booting_Screen_screen_destroy(void)
{
    if(ui_Booting_Screen) lv_obj_del(ui_Booting_Screen);

    // NULL screen variables
    uic_Booting_Screen = NULL;
    ui_Booting_Screen = NULL;
    uic_Image3 = NULL;
    ui_Image3 = NULL;

}
