// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: IoT TGG lcd tft

#ifndef UI_HOME_PAGE_H
#define UI_HOME_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home_Page
extern void ui_Home_Page_screen_init(void);
extern void ui_Home_Page_screen_destroy(void);
extern lv_obj_t * ui_Home_Page;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_header;
extern void ui_event_Roller2(lv_event_t * e);
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_moisture;
extern lv_obj_t * ui_moisture1;
extern lv_obj_t * ui_moisture2;
extern lv_obj_t * ui_moisture3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Chart3_Xaxis;
extern lv_obj_t * ui_Chart3_Yaxis1;
extern lv_obj_t * ui_Chart3_Yaxis2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Home_Page;
extern lv_obj_t * uic_header;
extern lv_obj_t * uic_moisture;
extern lv_obj_t * uic_Chart3;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

