// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: IoT TGG lcd tft

#include "ui.h"

lv_obj_t * uic_Chart3;
lv_obj_t * uic_moisture;
lv_obj_t * uic_header;
lv_obj_t * uic_Home_Page;
lv_obj_t * ui_Home_Page = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_Roller2 = NULL;
lv_obj_t * ui_moisture = NULL;
lv_obj_t * ui_moisture1 = NULL;
lv_obj_t * ui_moisture2 = NULL;
lv_obj_t * ui_moisture3 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Chart3 = NULL;
lv_obj_t * ui_Chart3_Xaxis = NULL;
lv_obj_t * ui_Chart3_Yaxis1 = NULL;
lv_obj_t * ui_Chart3_Yaxis2 = NULL;
// event funtions
void ui_event_Roller2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_screen_change(&ui_Settings_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings_Screen_screen_init);
    }
}

// build funtions

void ui_Home_Page_screen_init(void)
{
    ui_Home_Page = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Home_Page, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background_light);
    ui_object_set_themeable_style_property(ui_Home_Page, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background_light);
    ui_object_set_themeable_style_property(ui_Home_Page, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_light_secondary);
    ui_object_set_themeable_style_property(ui_Home_Page, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_light_secondary);
    lv_obj_set_style_border_width(ui_Home_Page, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Home_Page, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Home_Page);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 82);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, -158);
    lv_obj_set_y(ui_Slider1, 82);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Slider1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_light_tersier_2);
    ui_object_set_themeable_style_property(ui_Slider1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_light_tersier_2);

    ui_object_set_themeable_style_property(ui_Slider1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_light_secondary);
    ui_object_set_themeable_style_property(ui_Slider1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_light_secondary);

    ui_object_set_themeable_style_property(ui_Slider1, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_Slider1, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bold_text_light);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_header = lv_label_create(ui_Home_Page);
    lv_obj_set_width(ui_header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_header, -1);
    lv_obj_set_y(ui_header, -137);
    lv_obj_set_align(ui_header, LV_ALIGN_CENTER);
    lv_label_set_text(ui_header, "The Green Guardian");
    lv_obj_set_style_text_color(ui_header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_header, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller2 = lv_roller_create(ui_Home_Page);
    lv_roller_set_options(ui_Roller2, "HOME\nSETTINGS\nSENSOR", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller2, 71);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, 172);
    lv_obj_set_y(ui_Roller2, 72);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Roller2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_light_secondary);
    ui_object_set_themeable_style_property(ui_Roller2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_light_secondary);
    ui_object_set_themeable_style_property(ui_Roller2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_Roller2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_bold_text_light);

    ui_object_set_themeable_style_property(ui_Roller2, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_light_tersier_2);
    ui_object_set_themeable_style_property(ui_Roller2, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_light_tersier_2);

    ui_moisture = lv_label_create(ui_Home_Page);
    lv_obj_set_width(ui_moisture, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_moisture, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_moisture, -168);
    lv_obj_set_y(ui_moisture, -16);
    lv_obj_set_align(ui_moisture, LV_ALIGN_CENTER);
    lv_label_set_text(ui_moisture, "rain sensor");
    ui_object_set_themeable_style_property(ui_moisture, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_moisture, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_bold_text_light);

    ui_moisture1 = lv_label_create(ui_Home_Page);
    lv_obj_set_width(ui_moisture1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_moisture1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_moisture1, -178);
    lv_obj_set_y(ui_moisture1, 43);
    lv_obj_set_align(ui_moisture1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_moisture1, "Air Temp");
    ui_object_set_themeable_style_property(ui_moisture1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_moisture1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_bold_text_light);

    ui_moisture2 = lv_label_create(ui_Home_Page);
    lv_obj_set_width(ui_moisture2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_moisture2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_moisture2, -168);
    lv_obj_set_y(ui_moisture2, 15);
    lv_obj_set_align(ui_moisture2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_moisture2, "Soil Mois");
    ui_object_set_themeable_style_property(ui_moisture2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_moisture2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_bold_text_light);

    ui_moisture3 = lv_label_create(ui_Home_Page);
    lv_obj_set_width(ui_moisture3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_moisture3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_moisture3, -170);
    lv_obj_set_y(ui_moisture3, -49);
    lv_obj_set_align(ui_moisture3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_moisture3, "Soil temp");
    ui_object_set_themeable_style_property(ui_moisture3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_moisture3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_bold_text_light);

    ui_Container1 = lv_obj_create(ui_Home_Page);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 238);
    lv_obj_set_height(ui_Container1, 159);
    lv_obj_set_x(ui_Container1, 55);
    lv_obj_set_y(ui_Container1, -32);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart3 = lv_chart_create(ui_Home_Page);
    lv_obj_set_width(ui_Chart3, 276);
    lv_obj_set_height(ui_Chart3, 100);
    lv_obj_set_x(ui_Chart3, 56);
    lv_obj_set_y(ui_Chart3, -42);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart3, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart3, 12);
    lv_chart_set_div_line_count(ui_Chart3, 3, 2);
    ui_object_set_themeable_style_property(ui_Chart3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_light_secondary);
    ui_object_set_themeable_style_property(ui_Chart3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_light_secondary);
    ui_object_set_themeable_style_property(ui_Chart3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_background_light);
    ui_object_set_themeable_style_property(ui_Chart3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_background_light);

    ui_Chart3_Xaxis = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart3_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart3_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart3_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart3,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart3_Xaxis, 5, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart3_Xaxis, 0, 7 > 0 ? 7 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart3_Xaxis, (7 > 0 ? 7 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Xaxis, 2 >= 1 ? 2 : 1);
    ui_Chart3_Yaxis1 = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart3_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart3_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart3_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart3,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart3_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart3_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart3_Yaxis2 = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart3_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart3_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart3_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart3,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart3_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart3_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart3_series_1 = lv_chart_add_series(ui_Chart3, lv_color_hex(0xF25656),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart3_series_1_array[] = { 60, 80, 70, 75, 80, 85, 90, 95, 90, 80, 76, 80 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_1, ui_Chart3_series_1_array);
    lv_chart_series_t * ui_Chart3_series_2 = lv_chart_add_series(ui_Chart3, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart3_series_2_array[] = { 10, 20, 40, 10, 20, 40, 20, 30, 20, 10 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_2, ui_Chart3_series_2_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart3, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart3, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Roller2, ui_event_Roller2, LV_EVENT_ALL, NULL);
    uic_Home_Page = ui_Home_Page;
    uic_header = ui_header;
    uic_moisture = ui_moisture;
    uic_Chart3 = ui_Chart3;

}

void ui_Home_Page_screen_destroy(void)
{
    if(ui_Home_Page) lv_obj_del(ui_Home_Page);

    // NULL screen variables
    uic_Home_Page = NULL;
    ui_Home_Page = NULL;
    ui_Slider1 = NULL;
    uic_header = NULL;
    ui_header = NULL;
    ui_Roller2 = NULL;
    uic_moisture = NULL;
    ui_moisture = NULL;
    ui_moisture1 = NULL;
    ui_moisture2 = NULL;
    ui_moisture3 = NULL;
    ui_Container1 = NULL;
    uic_Chart3 = NULL;
    ui_Chart3 = NULL;

}
