// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: IoT TGG lcd tft

#ifndef UI_SETTINGS_SCREEN_H
#define UI_SETTINGS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings_Screen
extern void ui_Settings_Screen_screen_init(void);
extern void ui_Settings_Screen_screen_destroy(void);
extern lv_obj_t * ui_Settings_Screen;
extern void ui_event_Roller3(lv_event_t * e);
extern lv_obj_t * ui_Roller3;
extern void ui_event_SW_TEMA(lv_event_t * e);
extern lv_obj_t * ui_SW_TEMA;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Settings_Screen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

