// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: IoT TGG lcd tft

#include "ui.h"

lv_obj_t * uic_Settings_Screen;
lv_obj_t * ui_Settings_Screen = NULL;
lv_obj_t * ui_Roller3 = NULL;
lv_obj_t * ui_SW_TEMA = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_Roller3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home_Page, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_Page_screen_init);
    }
}

void ui_event_SW_TEMA(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_DARK);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_LIGHT);
    }
}

// build funtions

void ui_Settings_Screen_screen_init(void)
{
    ui_Settings_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Settings_Screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background_light);
    ui_object_set_themeable_style_property(ui_Settings_Screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background_light);
    ui_object_set_themeable_style_property(ui_Settings_Screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_light_secondary);
    ui_object_set_themeable_style_property(ui_Settings_Screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_light_secondary);
    lv_obj_set_style_border_width(ui_Settings_Screen, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Settings_Screen, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller3 = lv_roller_create(ui_Settings_Screen);
    lv_roller_set_options(ui_Roller3, "HOME\nSETTINGS\nSENSOR", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Roller3, 1, LV_ANIM_OFF);
    lv_obj_set_height(ui_Roller3, 71);
    lv_obj_set_width(ui_Roller3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller3, 172);
    lv_obj_set_y(ui_Roller3, 72);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Roller3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_light_secondary);
    ui_object_set_themeable_style_property(ui_Roller3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_light_secondary);
    ui_object_set_themeable_style_property(ui_Roller3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_Roller3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_bold_text_light);

    ui_object_set_themeable_style_property(ui_Roller3, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_light_tersier_2);
    ui_object_set_themeable_style_property(ui_Roller3, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_light_tersier_2);

    ui_SW_TEMA = lv_switch_create(ui_Settings_Screen);
    lv_obj_set_width(ui_SW_TEMA, 50);
    lv_obj_set_height(ui_SW_TEMA, 25);
    lv_obj_set_x(ui_SW_TEMA, -159);
    lv_obj_set_y(ui_SW_TEMA, 49);
    lv_obj_set_align(ui_SW_TEMA, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_SW_TEMA, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_SW_TEMA, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bold_text_light);

    ui_object_set_themeable_style_property(ui_SW_TEMA, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_SW_TEMA, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bold_text_light);
    ui_object_set_themeable_style_property(ui_SW_TEMA, LV_PART_INDICATOR | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_SW_TEMA, LV_PART_INDICATOR | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bold_text_light);

    ui_object_set_themeable_style_property(ui_SW_TEMA, LV_PART_KNOB | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_SW_TEMA, LV_PART_KNOB | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bold_text_light);

    ui_Label5 = lv_label_create(ui_Settings_Screen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -159);
    lv_obj_set_y(ui_Label5, 28);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "L / D mode");
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_bold_text_light);
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_bold_text_light);

    lv_obj_add_event_cb(ui_Roller3, ui_event_Roller3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SW_TEMA, ui_event_SW_TEMA, LV_EVENT_ALL, NULL);
    uic_Settings_Screen = ui_Settings_Screen;

}

void ui_Settings_Screen_screen_destroy(void)
{
    if(ui_Settings_Screen) lv_obj_del(ui_Settings_Screen);

    // NULL screen variables
    uic_Settings_Screen = NULL;
    ui_Settings_Screen = NULL;
    ui_Roller3 = NULL;
    ui_SW_TEMA = NULL;
    ui_Label5 = NULL;

}
