// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: IoT TGG lcd tft

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_background_light[3] = {0xD1D7C9, 0xD1D7C9, 0x2E2E2E};
const ui_theme_variable_t _ui_theme_alpha_background_light[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_bold_text_light[3] = {0x546B4D, 0x546B4D, 0xFF970D};
const ui_theme_variable_t _ui_theme_alpha_bold_text_light[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_light_secondary[3] = {0x3E5243, 0x3E5243, 0xF89B41};
const ui_theme_variable_t _ui_theme_alpha_light_secondary[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_light_tersier_2[3] = {0x819B62, 0x819B62, 0x292781};
const ui_theme_variable_t _ui_theme_alpha_light_tersier_2[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_LIGHT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

