// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: IoT TGG lcd tft

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BACKGROUND_LIGHT 0
#define UI_THEME_COLOR_BOLD_TEXT_LIGHT 1
#define UI_THEME_COLOR_LIGHT_SECONDARY 2
#define UI_THEME_COLOR_LIGHT_TERSIER_2 3

#define UI_THEME_DEFAULT 0

#define UI_THEME_LIGHT 1

#define UI_THEME_DARK 2

extern const ui_theme_variable_t _ui_theme_color_background_light[3];
extern const ui_theme_variable_t _ui_theme_alpha_background_light[3];

extern const ui_theme_variable_t _ui_theme_color_bold_text_light[3];
extern const ui_theme_variable_t _ui_theme_alpha_bold_text_light[3];

extern const ui_theme_variable_t _ui_theme_color_light_secondary[3];
extern const ui_theme_variable_t _ui_theme_alpha_light_secondary[3];

extern const ui_theme_variable_t _ui_theme_color_light_tersier_2[3];
extern const ui_theme_variable_t _ui_theme_alpha_light_tersier_2[3];

extern const uint32_t * ui_theme_colors[3];
extern const uint8_t * ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
